### ISSUE TITLE
Do Legacy Plugins work?

### ISSUE THREAD

**Issue by tkrtz** [Hypfer/esp8266-deerma-humidifier#1]
First of all: wow, just wow.
I bought this exact humidifier two months ago and didn't find any open-source firmware for that. Now stumbled upon your work. Your documentation is amazing and should make the installation pretty easy.

So, is it still possible for other software to communicate with the flashed humidifier. For instance the home bridge plugin? Or is there no other way around using mqtt?
I'm currently just blocking internet access for my humidifier to combat unneeded data exchange.

Needless to say, Grüße aus Hannover!

**Comment by Hypfer** [comment]
Glad to hear that it is easy to understand and follow :)

There's no way around using mqtt. The old firmware including the miio communication used by the home bridge plugin is permanently gone when using this firmware
