### ISSUE TITLE
management via mqtt does not work

### ISSUE THREAD

**Issue by ws23pro** [Hypfer/esp8266-deerma-humidifier#3]
hi!
I apologize in advance for my English: I'm using a translator :)

compiled the firmware, flashed the board, everything is fine. but the control via the topic / command does not work.
the topic /state shows the values, but they are not relevant. the only thing that works correctly is the topic /status when the device is turned on, the status "online" when I turn it off, changes to "offline". in the topic /command I send a json request from the example {"led":"off"}, but nothing happens.
I ask for help, maybe there are some thoughts

**Comment by cristi2005** [comment]
Hello, i put MQTT IP adderss 192.168.40:1883 from my Homeassistant server and not communicate with Humidifier.
On IP address need to put port 1883 or only ip ?
Thank for your's works.
Cristi

**Comment by ws23pro** [comment]
> Hello, i put MQTT IP adderss 192.168.40:1883 from my Homeassistant server and not communicate with Humidifier. On IP address need to put port 1883 or only ip ? Thank for your's works. Cristi

only ip!
if your mqtt server is not configured on a different port

**Comment by cristi2005** [comment]
Ok, Thank you.

**Comment by ws23pro** [comment]
> Ok, Thank you.

did you succeed?

**Comment by cristi2005** [comment]
Yes, in Homeassistant work great.


Trimis din Yahoo Mail pentru iPhone


La sâmbătă, ianuarie 29, 2022, 2:49 p.m., ws23pro ***@***.***> a scris:





Ok, Thank you.


did you succeed?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ws23pro** [comment]
> Yes, in Homeassistant work great. Trimis din Yahoo Mail pentru iPhone La sâmbătă, ianuarie 29, 2022, 2:49 p.m., ws23pro ***@***.***> a scris: Ok, Thank you. did you succeed? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

can you check the work through mqtt explorer ?

**Comment by cristi2005** [comment]
For the moment don't have Xiaomi Humidifier, i have only ESP board. I next week i want to order a humidifier to modify with this software to work in Homeassistant.

**Comment by cucpo** [comment]
I confirm that MQTT is not working. I still have an older one and it works OK.

**Comment by ws23pro** [comment]
> I confirm that MQTT is not working. I still have an older one and it works OK.

who is older? :)

**Comment by cucpo** [comment]
Sorry for my English. I thought I had a second humidifier for about half a year, flashed by your firmware and it works fine.

**Comment by ws23pro** [comment]
> Sorry for my English. I thought I had a second humidifier for about half a year, flashed by your firmware and it works fine.

my English also leaves much to be desired :D what is your version in the end? 1 or 2 ?

**Comment by cucpo** [comment]
Only now have I noticed that you have two versions. It works 2021.01.1, it doesn't work 2021.11.0. I will try flash 2021.01.1

**Comment by ws23pro** [comment]
> Only now have I noticed that you have two versions. It works 2021.01.1, it doesn't work 2021.11.0. I will try flash 2021.01.1

friend, I am not the author of the firmware, I am the same sufferer as you :)) what's your version of a humidifier? if the first one, could you reset the original firmware for me? I made a copy incorrectly:(

**Comment by cucpo** [comment]
Sorry i dont have original xiaomi fw :-(

**Comment by ws23pro** [comment]
> Only now have I noticed that you have two versions. It works 2021.01.1, it doesn't work 2021.11.0. I will try flash 2021.01.1

how are you doing with the version 2021.01.1?

**Comment by cucpo** [comment]
I have tried all commits but none work

**Comment by ws23pro** [comment]
> I have tried all commits but none work

sadly. if you can find something, let me know
