### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kopiro** [Hypfer/esp8266-deerma-humidifier#4]
hey; i just bought the humidifier and found this plugin; I wanted to understand if this replace the firmware entirely with all the associated functions (like starting when the humidity is low, etc...)

**Comment by Hypfer** [comment]
It only repaces the firmware of the wifi module.

The whole business-logic of the humidifier is done by a different uC with its own firmware.
Wi-Fi module and the other uC talk to each other via uart

**Comment by kopiro** [comment]
That is awesome! 

I don't use home assistant, I use home bridge instead, I'm not sure if your firmware is already compatible with homebridge-mqtthing but I guess I can just modify to work with it, right?

**Comment by Hypfer** [comment]
No idea. I'm honestly not a big fan of that whole apple golden cage thing

**Comment by kopiro** [comment]
Yeah I see. in the end it talks with using mqtt, I just need to configure the topics and the data format.

I'll let you know!

**Comment by Hypfer** [comment]
One annoying quirk of that humidifier is that it resets the target humidity to 54% every time you toggle between setpoint and any other option (low, med, high).

Your code might need to be aware of that

**Comment by kopiro** [comment]
Is this not a problem with home assistant or is it a problem there as well?

Where is this bug coming from?

**Comment by kopiro** [comment]
A related question: can I actually back up the firmware before flashing it?

**Comment by Hypfer** [comment]
> Where is this bug coming from?

The firmware of the device.

> can I actually back up the firmware before flashing it?

No idea

**Comment by kopiro** [comment]
Thanks then! 😉
